
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDEASSIGN COMMA DIVIDE ID INT LPAREN MINUS NUMBER PLUS RETURN RPAREN SEMICOLON TIMESprogram : statementsstatements : statementstatements : statements statementstatement : declaration\n| assignment\n| return_stmtdeclaration : INT declarator_list SEMICOLONdeclarator_list : declaratordeclarator_list : declarator_list COMMA declaratordeclarator : ID\n| ID ASSIGN expressionassignment : ID ASSIGN expression SEMICOLONreturn_stmt : RETURN expression SEMICOLONexpression : expression PLUS term\n| expression MINUS termexpression : termterm : term TIMES factor\n| term DIVIDE factorterm : factorfactor : NUMBER\n| ID\n| LPAREN expression RPAREN'
    
_lr_action_items = {'INT':([0,2,3,4,5,6,10,21,25,33,],[7,7,-2,-4,-5,-6,-3,-7,-13,-12,]),'ID':([0,2,3,4,5,6,7,9,10,14,20,21,22,23,25,26,27,28,29,33,],[8,8,-2,-4,-5,-6,13,19,-3,19,19,-7,13,19,-13,19,19,19,19,-12,]),'RETURN':([0,2,3,4,5,6,10,21,25,33,],[9,9,-2,-4,-5,-6,-3,-7,-13,-12,]),'$end':([1,2,3,4,5,6,10,21,25,33,],[0,-1,-2,-4,-5,-6,-3,-7,-13,-12,]),'ASSIGN':([8,13,],[14,23,]),'NUMBER':([9,14,20,23,26,27,28,29,],[18,18,18,18,18,18,18,18,]),'LPAREN':([9,14,20,23,26,27,28,29,],[20,20,20,20,20,20,20,20,]),'SEMICOLON':([11,12,13,15,16,17,18,19,24,31,32,34,35,36,37,38,],[21,-8,-10,25,-16,-19,-20,-21,33,-9,-11,-14,-15,-17,-18,-22,]),'COMMA':([11,12,13,16,17,18,19,31,32,34,35,36,37,38,],[22,-8,-10,-16,-19,-20,-21,-9,-11,-14,-15,-17,-18,-22,]),'PLUS':([15,16,17,18,19,24,30,32,34,35,36,37,38,],[26,-16,-19,-20,-21,26,26,26,-14,-15,-17,-18,-22,]),'MINUS':([15,16,17,18,19,24,30,32,34,35,36,37,38,],[27,-16,-19,-20,-21,27,27,27,-14,-15,-17,-18,-22,]),'RPAREN':([16,17,18,19,30,34,35,36,37,38,],[-16,-19,-20,-21,38,-14,-15,-17,-18,-22,]),'TIMES':([16,17,18,19,34,35,36,37,38,],[28,-19,-20,-21,28,28,-17,-18,-22,]),'DIVIDE':([16,17,18,19,34,35,36,37,38,],[29,-19,-20,-21,29,29,-17,-18,-22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statements':([0,],[2,]),'statement':([0,2,],[3,10,]),'declaration':([0,2,],[4,4,]),'assignment':([0,2,],[5,5,]),'return_stmt':([0,2,],[6,6,]),'declarator_list':([7,],[11,]),'declarator':([7,22,],[12,31,]),'expression':([9,14,20,23,],[15,24,30,32,]),'term':([9,14,20,23,26,27,],[16,16,16,16,34,35,]),'factor':([9,14,20,23,26,27,28,29,],[17,17,17,17,17,17,36,37,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statements','program',1,'p_program','parser.py',94),
  ('statements -> statement','statements',1,'p_statements_single','parser.py',99),
  ('statements -> statements statement','statements',2,'p_statements_multiple','parser.py',104),
  ('statement -> declaration','statement',1,'p_statement','parser.py',109),
  ('statement -> assignment','statement',1,'p_statement','parser.py',110),
  ('statement -> return_stmt','statement',1,'p_statement','parser.py',111),
  ('declaration -> INT declarator_list SEMICOLON','declaration',3,'p_declaration','parser.py',116),
  ('declarator_list -> declarator','declarator_list',1,'p_declarator_list_single','parser.py',121),
  ('declarator_list -> declarator_list COMMA declarator','declarator_list',3,'p_declarator_list_multiple','parser.py',126),
  ('declarator -> ID','declarator',1,'p_declarator','parser.py',131),
  ('declarator -> ID ASSIGN expression','declarator',3,'p_declarator','parser.py',132),
  ('assignment -> ID ASSIGN expression SEMICOLON','assignment',4,'p_assignment','parser.py',140),
  ('return_stmt -> RETURN expression SEMICOLON','return_stmt',3,'p_return_stmt','parser.py',145),
  ('expression -> expression PLUS term','expression',3,'p_expression_binop','parser.py',150),
  ('expression -> expression MINUS term','expression',3,'p_expression_binop','parser.py',151),
  ('expression -> term','expression',1,'p_expression_term','parser.py',156),
  ('term -> term TIMES factor','term',3,'p_term_binop','parser.py',161),
  ('term -> term DIVIDE factor','term',3,'p_term_binop','parser.py',162),
  ('term -> factor','term',1,'p_term_factor','parser.py',167),
  ('factor -> NUMBER','factor',1,'p_factor','parser.py',172),
  ('factor -> ID','factor',1,'p_factor','parser.py',173),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor','parser.py',174),
]
